# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resources.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resources.proto',
  package='DATACELL',
  syntax='proto2',
  serialized_pb=_b('\n\x0fresources.proto\x12\x08\x44\x41TACELL\"o\n\x0fResourceDemande\x12\x14\n\x0cresourceName\x18\x01 \x02(\t\x12\x15\n\rresourceCount\x18\x02 \x02(\x05\x12/\n\x08strategy\x18\x03 \x02(\x0e\x32\x1d.DATACELL.Allocation_Strategy\":\n\x0cResourceInfo\x12\x14\n\x0cresourceName\x18\x01 \x02(\t\x12\x14\n\x0cresourceInfo\x18\x02 \x02(\t\"e\n\x0fResourceRequest\x12\x10\n\x08\x63lientID\x18\x01 \x02(\t\x12\x13\n\x0brequestType\x18\x02 \x02(\t\x12+\n\x08requests\x18\x03 \x03(\x0b\x32\x19.DATACELL.ResourceDemande\"A\n\x10ResourceResponse\x12-\n\rresourceInfos\x18\x01 \x03(\x0b\x32\x16.DATACELL.ResourceInfo*T\n\x13\x41llocation_Strategy\x12\x1e\n\x1a\x41llocation_Strategy_Random\x10\x01\x12\x1d\n\x19\x41llocation_Strategy_Fixed\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ALLOCATION_STRATEGY = _descriptor.EnumDescriptor(
  name='Allocation_Strategy',
  full_name='DATACELL.Allocation_Strategy',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Allocation_Strategy_Random', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Allocation_Strategy_Fixed', index=1, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=372,
  serialized_end=456,
)
_sym_db.RegisterEnumDescriptor(_ALLOCATION_STRATEGY)

Allocation_Strategy = enum_type_wrapper.EnumTypeWrapper(_ALLOCATION_STRATEGY)
Allocation_Strategy_Random = 1
Allocation_Strategy_Fixed = 2



_RESOURCEDEMANDE = _descriptor.Descriptor(
  name='ResourceDemande',
  full_name='DATACELL.ResourceDemande',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resourceName', full_name='DATACELL.ResourceDemande.resourceName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resourceCount', full_name='DATACELL.ResourceDemande.resourceCount', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='DATACELL.ResourceDemande.strategy', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=140,
)


_RESOURCEINFO = _descriptor.Descriptor(
  name='ResourceInfo',
  full_name='DATACELL.ResourceInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resourceName', full_name='DATACELL.ResourceInfo.resourceName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resourceInfo', full_name='DATACELL.ResourceInfo.resourceInfo', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=200,
)


_RESOURCEREQUEST = _descriptor.Descriptor(
  name='ResourceRequest',
  full_name='DATACELL.ResourceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clientID', full_name='DATACELL.ResourceRequest.clientID', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requestType', full_name='DATACELL.ResourceRequest.requestType', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requests', full_name='DATACELL.ResourceRequest.requests', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=303,
)


_RESOURCERESPONSE = _descriptor.Descriptor(
  name='ResourceResponse',
  full_name='DATACELL.ResourceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='resourceInfos', full_name='DATACELL.ResourceResponse.resourceInfos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=370,
)

_RESOURCEDEMANDE.fields_by_name['strategy'].enum_type = _ALLOCATION_STRATEGY
_RESOURCEREQUEST.fields_by_name['requests'].message_type = _RESOURCEDEMANDE
_RESOURCERESPONSE.fields_by_name['resourceInfos'].message_type = _RESOURCEINFO
DESCRIPTOR.message_types_by_name['ResourceDemande'] = _RESOURCEDEMANDE
DESCRIPTOR.message_types_by_name['ResourceInfo'] = _RESOURCEINFO
DESCRIPTOR.message_types_by_name['ResourceRequest'] = _RESOURCEREQUEST
DESCRIPTOR.message_types_by_name['ResourceResponse'] = _RESOURCERESPONSE
DESCRIPTOR.enum_types_by_name['Allocation_Strategy'] = _ALLOCATION_STRATEGY

ResourceDemande = _reflection.GeneratedProtocolMessageType('ResourceDemande', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCEDEMANDE,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:DATACELL.ResourceDemande)
  ))
_sym_db.RegisterMessage(ResourceDemande)

ResourceInfo = _reflection.GeneratedProtocolMessageType('ResourceInfo', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCEINFO,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:DATACELL.ResourceInfo)
  ))
_sym_db.RegisterMessage(ResourceInfo)

ResourceRequest = _reflection.GeneratedProtocolMessageType('ResourceRequest', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCEREQUEST,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:DATACELL.ResourceRequest)
  ))
_sym_db.RegisterMessage(ResourceRequest)

ResourceResponse = _reflection.GeneratedProtocolMessageType('ResourceResponse', (_message.Message,), dict(
  DESCRIPTOR = _RESOURCERESPONSE,
  __module__ = 'resources_pb2'
  # @@protoc_insertion_point(class_scope:DATACELL.ResourceResponse)
  ))
_sym_db.RegisterMessage(ResourceResponse)


# @@protoc_insertion_point(module_scope)
